export const INIT = 'INIT_ACTION';
export const AUTH_CLOSE = 'AUTH_CLOSE';
export const AUTH_SUBMIT = 'AUTH_SUBMIT';
export const CHAT_CLOSE = 'CHAT_CLOSE';
export const CHAT_SEND_MESSAGE = 'CHAT_SEND_MESSAGE';
export const CHAT_MESSAGE_WRITING = 'CHAT_MESSAGE_WRITING';
export const CHAT_MESSAGE_STOP_WRITING = 'CHAT_MESSAGE_STOP_WRITING';
